# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refilm', '0002_auto_20160703_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movieId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
