# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refilm', '0003_movie_movieid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movieId',
            new_name='imdbID',
        ),
    ]
